{"filename": "usage.rst", "lineno": 73, "status": "unchecked", "code": 0, "uri": "#pytest_memray.LeaksFilteringFunction", "info": ""}
{"filename": "news.rst", "lineno": 64, "status": "broken", "code": 0, "uri": "https://github.com/bloomberg/pytest-memray/issues/10", "info": "HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /bloomberg/pytest-memray/issues/10 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)')))"}
{"filename": "usage.rst", "lineno": 101, "status": "broken", "code": 0, "uri": "https://bloomberg.github.io/memray/getting_started.html", "info": "HTTPSConnectionPool(host='bloomberg.github.io', port=443): Max retries exceeded with url: /memray/getting_started.html (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)')))"}
{"filename": "news.rst", "lineno": 56, "status": "broken", "code": 0, "uri": "https://github.com/ChaoticRoman", "info": "HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /ChaoticRoman (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)')))"}
{"filename": "news.rst", "lineno": 66, "status": "broken", "code": 0, "uri": "https://github.com/bloomberg/pytest-memray/issues/11", "info": "HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /bloomberg/pytest-memray/issues/11 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)')))"}
{"filename": "usage.rst", "lineno": 56, "status": "working", "code": 0, "uri": "https://docs.python.org/3/c-api/memory.html", "info": ""}
{"filename": "news.rst", "lineno": 54, "status": "broken", "code": 0, "uri": "https://github.com/bloomberg/pytest-memray/issues/12", "info": "HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /bloomberg/pytest-memray/issues/12 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)')))"}
{"filename": "news.rst", "lineno": 75, "status": "broken", "code": 0, "uri": "https://github.com/bloomberg/pytest-memray/issues/20", "info": "HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /bloomberg/pytest-memray/issues/20 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)')))"}
{"filename": "news.rst", "lineno": 41, "status": "broken", "code": 0, "uri": "https://github.com/bloomberg/pytest-memray/issues/18", "info": "HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /bloomberg/pytest-memray/issues/18 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)')))"}
{"filename": "news.rst", "lineno": 55, "status": "broken", "code": 0, "uri": "https://github.com/bloomberg/pytest-memray/issues/26", "info": "HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /bloomberg/pytest-memray/issues/26 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)')))"}
{"filename": "news.rst", "lineno": 48, "status": "broken", "code": 0, "uri": "https://github.com/bloomberg/pytest-memray/issues/28", "info": "HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /bloomberg/pytest-memray/issues/28 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)')))"}
{"filename": "news.rst", "lineno": 71, "status": "broken", "code": 0, "uri": "https://github.com/bloomberg/pytest-memray/issues/3", "info": "HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /bloomberg/pytest-memray/issues/3 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)')))"}
{"filename": "news.rst", "lineno": 63, "status": "broken", "code": 0, "uri": "https://github.com/bloomberg/pytest-memray/issues/5", "info": "HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /bloomberg/pytest-memray/issues/5 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)')))"}
{"filename": "news.rst", "lineno": 56, "status": "broken", "code": 0, "uri": "https://github.com/bloomberg/pytest-memray/issues/30", "info": "HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /bloomberg/pytest-memray/issues/30 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)')))"}
{"filename": "news.rst", "lineno": 13, "status": "broken", "code": 0, "uri": "https://github.com/bloomberg/pytest-memray/issues/57", "info": "HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /bloomberg/pytest-memray/issues/57 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)')))"}
{"filename": "news.rst", "lineno": 14, "status": "broken", "code": 0, "uri": "https://github.com/bloomberg/pytest-memray/issues/58", "info": "HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /bloomberg/pytest-memray/issues/58 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)')))"}
{"filename": "news.rst", "lineno": 41, "status": "broken", "code": 0, "uri": "https://github.com/gaborbernat", "info": "HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /gaborbernat (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)')))"}
{"filename": "news.rst", "lineno": 63, "status": "broken", "code": 0, "uri": "https://github.com/petr-tik", "info": "HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /petr-tik (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)')))"}
{"filename": "news.rst", "lineno": 18, "status": "broken", "code": 0, "uri": "https://github.com/bloomberg/pytest-memray/issues/60", "info": "HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /bloomberg/pytest-memray/issues/60 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1002)')))"}
